

2018-11-29 09:53:47,684 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 09:54:54,994 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 09:54:54,995 - INFO - ginger.py - framework_error - 21 - get() takes 2 positional arguments but 3 were given
2018-11-29 09:56:12,504 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 09:56:53,708 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 09:59:01,878 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 09:59:27,183 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 09:59:27,185 - INFO - ginger.py - framework_error - 21 - division by zero
2018-11-29 10:00:59,674 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:00:59,677 - ERROR - ginger.py - framework_error - 19 - division by zero
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\FlaskStudy\flaskAPI\app\api\v1\book_api.py", line 36, in get_redis_wyy
    1 / 0
ZeroDivisionError: division by zero
2018-11-29 10:03:26,516 - INFO - __init__.py - before_request - 69 - [POST] /v1/book/all_book 无参
2018-11-29 10:03:29,476 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:32,103 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:33,985 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:35,362 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:36,552 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:37,467 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:37,470 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 1 per 1 second
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 1 per 1 second
2018-11-29 10:03:38,399 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:39,948 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:41,297 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:42,572 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:43,715 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:43,716 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 10 per 1 minute
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 10 per 1 minute
2018-11-29 10:03:46,100 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:46,102 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 10 per 1 minute
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 10 per 1 minute
2018-11-29 10:03:47,465 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:03:47,466 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 10 per 1 minute
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 10 per 1 minute
2018-11-29 10:04:33,914 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:04:36,152 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:04:39,940 - INFO - __init__.py - before_request - 69 - [POST] /v1/book/all_book 无参
2018-11-29 10:04:41,812 - INFO - __init__.py - before_request - 69 - [POST] /v1/book/all_book 无参
2018-11-29 10:04:44,666 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:04:46,821 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:05:45,197 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 10:05:48,143 - INFO - __init__.py - before_request - 69 - [POST] /v1/book/all_book 无参
2018-11-29 10:05:50,748 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 12:52:42,693 - INFO - run.py - <module> - 12 - 服务正在启动中...
2018-11-29 12:53:50,978 - INFO - run.py - <module> - 12 - 服务正在启动中...
2018-11-29 12:56:20,682 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 12:57:04,735 - INFO - __init__.py - before_request - 69 - [POST] /v1/user/super_get_user/9222bbc0bfdd41fda38f1a8dd3a24d4 无参
2018-11-29 12:57:04,740 - ERROR - ginger.py - framework_error - 19 - 404 Not Found: 用户未找到
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_httpauth.py", line 104, in decorated
    return f(*args, **kwargs)
  File "D:\FlaskStudy\flaskAPI\app\api\v1\user_api.py", line 18, in super_get_user
    user = UserModel.query.filter_by(id=uid).first_or_404()
  File "D:\FlaskStudy\flaskAPI\app\models\base_model.py", line 37, in first_or_404
    raise UserNotFoundException()
app.libs.wyy_exception.UserNotFoundException: 404 Not Found: 用户未找到
2018-11-29 12:57:58,651 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 105}
2018-11-29 12:57:58,652 - ERROR - ginger.py - framework_error - 19 - 400 Bad Request: {'type': ['105 is not a valid ClientTypeEnum']}
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\FlaskStudy\flaskAPI\app\api\v1\token_api.py", line 18, in get_token
    form = ClientForm().validate_for_api()
  File "D:\FlaskStudy\flaskAPI\app\validates\base_form.py", line 17, in validate_for_api
    raise ParameterException(msg=self.errors)
app.libs.wyy_exception.ParameterException: 400 Bad Request: {'type': ['105 is not a valid ClientTypeEnum']}
2018-11-29 12:58:08,165 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 14:32:07,162 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 14:44:29,586 - INFO - run.py - <module> - 12 - 服务正在启动中...
2018-11-29 14:44:39,163 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 14:44:43,061 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:50,508 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:52,562 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:53,338 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:53,340 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 1 per 1 second
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 1 per 1 second
2018-11-29 14:44:54,228 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:55,246 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:56,089 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:56,092 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 1 per 1 second
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 1 per 1 second
2018-11-29 14:44:58,023 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:59,062 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:59,860 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:44:59,862 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 1 per 1 second
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 1 per 1 second
2018-11-29 14:45:01,082 - INFO - __init__.py - before_request - 69 - [GET] /v1/book/get_redis_wyy 无参
2018-11-29 14:45:01,085 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 10 per 1 minute
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 10 per 1 minute
2018-11-29 15:03:25,457 - INFO - run.py - <module> - 12 - 服务正在启动中...
2018-11-29 15:07:34,307 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token 无参
2018-11-29 15:07:34,309 - ERROR - ginger.py - framework_error - 19 - 400 Bad Request: {'account': ['账号为必传选项'], 'type': ['This field is required.']}
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\FlaskStudy\flaskAPI\app\api\v1\token_api.py", line 18, in get_token
    form = ClientForm().validate_for_api()
  File "D:\FlaskStudy\flaskAPI\app\validates\base_form.py", line 17, in validate_for_api
    raise ParameterException(msg=self.errors)
app.libs.wyy_exception.ParameterException: 400 Bad Request: {'account': ['账号为必传选项'], 'type': ['This field is required.']}
2018-11-29 15:07:44,065 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:07:44,072 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:07:44,074 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 1 per 1 second
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 1 per 1 second
2018-11-29 15:07:56,767 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:07:56,774 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:07:56,776 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 1 per 1 second
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 1 per 1 second
2018-11-29 15:07:58,109 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:08:03,523 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:08:03,552 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:08:03,555 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 1 per 1 second
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 1 per 1 second
2018-11-29 15:08:34,972 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:08:35,001 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:08:35,003 - ERROR - ginger.py - framework_error - 19 - 429 Too Many Requests: 1 per 1 second
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask_limiter\extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
werkzeug.exceptions.TooManyRequests: 429 Too Many Requests: 1 per 1 second
2018-11-29 15:09:57,004 - INFO - run.py - <module> - 12 - 服务正在启动中...
2018-11-29 15:10:02,127 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:10:02,156 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:11:10,438 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:11:10,465 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:12:17,526 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:12:17,558 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:25:22,686 - INFO - __init__.py - before_request - 69 - [GET] /deliveryFive/ 无参
2018-11-29 15:25:22,688 - ERROR - ginger.py - framework_error - 19 - 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\werkzeug\routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
2018-11-29 15:25:22,970 - INFO - __init__.py - before_request - 69 - [GET] /deliveryFive/favicon.ico 无参
2018-11-29 15:25:22,971 - ERROR - ginger.py - framework_error - 19 - 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\flask\ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "C:\Users\Administrator\.virtualenvs\flaskAPI-Fur5vEuz\lib\site-packages\werkzeug\routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
2018-11-29 15:27:18,818 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:27:18,837 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:27:22,331 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:33:05,395 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:33:05,408 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:34:34,132 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:34:34,147 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 15:44:25,017 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 15:44:25,047 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:43:22,125 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 16:43:22,139 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:43:26,291 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:44:35,450 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 16:44:35,463 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:44:37,826 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:45:43,480 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 16:45:43,492 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:46:39,829 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 16:46:39,841 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:46:40,854 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:46:41,673 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:47:30,368 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 16:47:30,380 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:47:31,561 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:47:32,382 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:47:33,340 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 16:47:39,635 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 16:47:39,653 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 17:00:54,252 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 17:00:54,284 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 17:04:49,986 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 17:04:49,998 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 17:05:59,008 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 17:05:59,023 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
2018-11-29 17:06:10,828 - INFO - __init__.py - before_request - 69 - [OPTIONS] /v1/token/get_token 无参
2018-11-29 17:06:10,842 - INFO - __init__.py - before_request - 69 - [POST] /v1/token/get_token {'account': '1023097281@qq.com', 'secret': '123456', 'type': 100}
